models/brand.py
class Brand:
    def __init__(self, name, id = None):
        self.name = name
        self.id = id

        

models/product.py
class Product:

    def __init__(self, type, in_stock, low_stock_threshold, buying_price, selling_price, supplier, brand, id = None):
        self.type = type
        self.in_stock = in_stock
        self.low_stock_threshold = low_stock_threshold
        self.buying_price = buying_price
        self.selling_price = selling_price
        self.supplier = supplier
        self.brand = brand
        self.id = id

    def get_details(self):
        return f"{self.type} {self.brand.name} {self.in_stock}"
        


    def calculate_mark_up(self):
        mark_up = 100 * (self.selling_price - self.buying_price) / self.buying_price 
        return round(mark_up, 2)   
          


    # method
    #   if stock is 0 Then
    #       "No Stock"
    #   elif stock is <= low stock threshold Then
    #       "Low Stock"
    #   else 
    #       "In Stock"

    def stock_level(self):

        if self.in_stock == 0:
            return "No Stock"
        elif self.in_stock <= self.low_stock_threshold:
            return "Low Stock"
        else: 
            return "In Stock"    

models/supplier.py
class Supplier:
    def __init__(self, name, contact, carraige_paid, id = None):
        self.name = name
        self.contact = contact
        self.carraige_paid = carraige_paid
        self.id = id

app.py
from flask import Flask, render_template

from controllers.brands_controller import brands_blueprint
from controllers.suppliers_controller import suppliers_blueprint
from controllers.products_controller import products_blueprint

app = Flask(__name__)

app.register_blueprint(brands_blueprint)
app.register_blueprint(suppliers_blueprint)
app.register_blueprint(products_blueprint)

@app.route('/')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)

controllers/brands_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint 
from models.brand import Brand
import repositories.brand_repository as brand_repository

brands_blueprint = Blueprint("brands", __name__)

@brands_blueprint.route("/brands")
def brands():
    brands = brand_repository.select_all()
    return render_template("brands/index.html", all_brands = brands)

    # NEW
# GET '/brands/new'  I DON'T KNOW IF I WANT THE ROUTES TO BE AS THEY ARE. 

@brands_blueprint.route("/brands/new", methods=['GET'])
def new_brand():
    return render_template("brands/new.html")
    


# CREATE
# POST '/brands'
@brands_blueprint.route("/brands", methods=['POST'])
def create_brand():
    name = request.form['name']
    brand = Brand(name)
    brand_repository.save(brand)
    return redirect('/brands')






# SHOW
# GET '/brands/<id>'

# EDIT
# GET '/brands/<id>/edit'


# UPDATE
# PUT '/brands /<id>'


# DELETE
# DELETE '/books/<id>'

controllers/products_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.product import Product

import repositories.product_repository as product_repository
import repositories.supplier_repository as supplier_repository
import repositories.brand_repository as brand_repository

products_blueprint = Blueprint("products", __name__)

# INDEX
# GET '/products'

@products_blueprint.route("/products")
def products():
    products = product_repository.select_all()
    return render_template("products/index.html", all_products = products)

# NEW
# GET '/products/new'

@products_blueprint.route("/products/new", methods=['GET'])
def new_product():
    suppliers = supplier_repository.select_all()
    brands = brand_repository.select_all()
    return render_template("products/new.html", all_suppliers = suppliers, all_brands = brands)
    
# CREATE 
# POST '/products'

@products_blueprint.route("/products", methods=['POST'])
def create_product():
    type = request.form['type']
    in_stock = request.form['in_stock']
    low_stock_threshold = request.form['low_stock_threshold']
    buying_price = request.form['buying_price']
    selling_price = request.form['selling_price']
    supplier = supplier_repository.select(request.form['supplier_id'])
    brand = brand_repository.select(request.form['brand_id'])
    product = Product(type, in_stock, low_stock_threshold, buying_price, selling_price, supplier, brand)
    product_repository.save(product)
    return redirect('/products')

# SHOW
# GET '/products/<id>'

@products_blueprint.route("/products/<id>", methods=['GET'])
def show_product(id):
    product = product_repository.select(id)
    return render_template('products/show.html', product = product)

# EDIT
# PUT '/products/<id>/edit'

# not sure about this function. edit? is it workking with update? 

@products_blueprint.route("/products/<id>/edit", methods=["GET"])
def edit_product(id):
    product = product_repository.select(id)
    brands = brand_repository.select_all()
    suppliers = supplier_repository.select_all()
    return render_template('products/edit.html', product = product, all_brands = brands, all_suppliers = suppliers) 


# UPDATE  
# PUT '/products/<id>
# do I need PRINT statements somewhere here?

@products_blueprint.route("/products/<id>", methods=['POST'])
def update_product(id):
    type = request.form['type']
    in_stock = request.form['in_stock']
    low_stock_threshold = request.form['low_stock_threshold']
    buying_price = request.form['buying_price']
    selling_price = request.form['selling_price']
    supplier = supplier_repository.select(request.form['supplier_id'])
    brand = brand_repository.select(request.form['brand_id'])
    product = Product(type, in_stock, low_stock_threshold, buying_price, selling_price, supplier, brand, id)
    product_repository.update(product)
    return redirect('/products')

# DELETE
# DELETE '/products/<id>'

@products_blueprint.route("/products/<id>/delete", methods=['POST'])
def delete_product(id):
    product_repository.delete(id)
    return redirect('/products')

controllers/suppliers_controller.py
from click import edit
from flask import Flask, render_template, request, redirect
from flask import Blueprint 
from models.supplier import Supplier
import repositories.supplier_repository as supplier_repository

suppliers_blueprint = Blueprint("suppliers", __name__)

# INDEX
# GET '/suppliers

@suppliers_blueprint.route("/suppliers")
def suppliers():
    suppliers = supplier_repository.select_all()
    return render_template("suppliers/index.html", all_suppliers = suppliers)

# NEW
# GET '/suppliers/new'  not sure about these paths

@suppliers_blueprint.route("/suppliers/new", methods=['GET'])
def new_supplier():

    return render_template("suppliers/new.html")

# CREATE
# POST '/suppliers'
@suppliers_blueprint.route("/suppliers", methods=['POST'])
def create_supplier():
    name = request.form['name']
    contact = request.form['contact']
    carraige_paid = request.form['carraige_paid']
    supplier = Supplier(name, contact, carraige_paid)
    supplier_repository.save(supplier)
    return redirect('/suppliers')
    
#SHOW
#GET '/suppliers/<id>

@suppliers_blueprint.route("/suppliers/<id>", methods=['GET'])    
def show_supplier(id):
    supplier = supplier_repository.select(id)
    return render_template('suppliers/show.html', supplier = supplier)


# EDIT
#GET '/suppliers/<id>/edit

@suppliers_blueprint.route("/suppliers/<id>/edit", methods=['GET'] )
def edit_supplier(id):
    supplier = supplier_repository.select(id)

    return render_template('suppliers/edit.html', supplier = supplier)


# UPDATE
#PUT'/suppliers/<id>

@suppliers_blueprint.route("/suppliers/<id>", methods=['POST'])
def update_suppliers(id):
    name = request.form['name']
    contact = request.form['contact']
    carraige_paid = request.form['carraige_paid']
    supplier = Supplier(name, contact, carraige_paid, id)
    supplier_repository.update(supplier)
    return redirect('/suppliers')


# DELETE
# DELETE '/WORKS/<ID>

@suppliers_blueprint.route("/supliers/<id>/delete", methods=['POST'])
def delete_suppliers(id):
    supplier_repository.delete(id)
    return redirect('/suppliers')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>Largs Hardware Inventory</title>
</head>
<body>
  <header>
    <nav>
      <ul class="menu">
        <a href="{{ url_for('home') }}"> Home </a>
        <a href="{{ url_for('products.products') }}"> Products </a>
        <a href="/products/new"> Add Product </a>
        <a href="{{ url_for('suppliers.suppliers') }}"> Suppliers </a>
        <a href="/suppliers/new"> Add Supplier </a>

        <a href="/brands"> Brands </a>

        <a href="/brands/new"> Add Brand </a>
        <a href="/suppliers"> Edit Suppliers </a>
   
        

        
      </ul>
    </nav>
  </header>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  {%block home%}
  {% endblock %}
</body>
</html>

templates/brands/index.html
{% extends 'base.html' %}
{% block content  %}  
<style>
table, th, td {
  border:1px solid black;
}
</style>
<body>

<h3>All Product Brands</h3>
  
<table style = "width:25%"">
  <tr>
    <th>Brand</th>
  
  </tr>
  

   
  {% for brand in all_brands %}
  <tr>
 

    <td>{{brand.name}}  </td>






  </tr>
  {% endfor %}

</table>


{% endblock content  %} 

templates/brands/new.html
{% extends "base.html" %}
{% block content %}
<h3>Add New Brand</h3> 
<form action="/brands" method="post">

  <div>
    <label for="brand">Brand Name:</label>
    <input type="text" id="brand" name="name" placeholder="brand" required autofocus />
  </div>


  <button type="submit">Add Brand</button>

</form>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block home %}
<img src="/../../static/images/Largs_Hardware.jpg" width="600" height="400" />
<section id="home-image">
 

</section>
{% endblock %}

templates/products/edit.html
{% extends "base.html" %}
{% block content %}

<h3>Edit Product </h3>

<form action="/products/{{product.id}}" method="post">
  <div>
    <label for="type">Type:</label>
    <input type="text" id="type" name="type" value="{{product.type}}" required>
  </div>

  <div>
    <label for="in_stock">In Stock:</label>
    <input type="number" id="in_stock" name="in_stock" value="{{product.in_stock}}" required />
  </div>
  <div>
    <label for="low_stock_threshold">Low Stock Threshold:</label>
    <input type="number" id="low_stock_threshold" name="low_stock_threshold" value="{{product.low_stock_threshold}}" required />
  </div>

  <div>
    <label for="buying_price">Buying Price:</label>
    <input type="number" id="buying_price" name="buying_price" value="{{product.buying_price}}" required />
  </div>

  <div>
    <label for="selling_price">Selling Price:</label>
    <input type="number" id="selling_price" name="selling_price" value="{{product.selling_price}}" required />
  </div>

  <div>
    <label for="supplier">Supplier:</label>
    <select id="supplier" name="supplier_id">
      {% for supplier in all_suppliers %}
        <option value="{{ supplier.id }}"
          {% if product.supplier.id == supplier.id %} selected="selected"{% endif %}>
          {{ supplier.name }}
        </option>
      {% endfor %}
    </select>
    <label for="brand">Brand:</label>
    <select id="brand" name="brand_id">
      {% for brand in all_brands %}
        <option value="{{ brand.id }}"
          {% if product.brand.id == brand.id %} selected="selected"{% endif %}>
          {{ brand.name }}
        </option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Update Product</button>

</form>

{% endblock %}

templates/products/index.html
{% extends 'base.html' %}
{% block content  %}  
<style>
table, th, td {
  border:1px solid black;
}
</style>
<body>

  <h3>All Products</h3>
  
<table style = "width:75%"
  <tr>
    <th>Type</th>
    <th>Brand</th>
    <th>In Stock</th>
    <th>Stock Level</th>
    <th>Buying</th>
    <th>Selling</th>
    <th>Mark Up</th>
    <th>Supplier</th>
  </tr>
  

   
  {% for product in all_products %}
  <tr>
    <td> <a href="/products/{{product.id}}/edit">{{product.type}}</a></td>
    <td> <a href="/brands">{{product.brand.name}}</a></td>
    <td>{{product.in_stock}}</td>
    <td>{{product.stock_level()}}</td>
    <td>{{product.buying_price}}</td>
    <td>{{product.selling_price}}</td>
    <td>{{product.calculate_mark_up()}}%</td>
    <td> <a href="/suppliers/{{product.supplier.id}}">{{product.supplier.name}}</a><td>
    <td> <a href="/products/{{product.id}}/edit">Edit Product</a></td>


  </tr>
  {% endfor %}

</table>

{% endblock content  %}  

templates/products/new.html
{% extends "base.html" %}
{% block content %}

<h3>Add New Product</h3>

<form class="form-inline" action="/products" method="post">

  <div>
    <label for="type">Type:</label>
    <input type="text" id="type" name="type" placeholder="type" required autofocus />
  </div>

  <div>
    <label for="in_stock">In Stock:</label>
    <input type="number" id="in_stock" name="in_stock" placeholder="in_stock" required />
  </div>
  <div>
    <label for="low_stock_threshold">Low Stock Threshold:</label>
    <input type="number" id="low_stock_threshold" name="low_stock_threshold" placeholder="low_stock_threshold" required autofocus />
  </div>

  <div>
    <label for="buying_price">Buying Price:</label>
    <input type="number" id="buying_price" name="buying_price" placeholder="buying_price" required />
  </div>

  <div>
    <label for="selling_price">Selling Price:</label>
    <input type="number" id="selling_price" name="selling_price" placeholder="selling_price" required />
  </div>
  <div>
    
    <label for="supplier">Supplier:</label>
    <select id="supplier" name="supplier_id">
      {% for supplier in all_suppliers %}
        <option value="{{ supplier.id }}">{{ supplier.name }}</option>
      {% endfor %}

    </select>
      <label for="brand">Brand:</label>
    <select id="brand" name="brand_id">
      {% for brand in all_brands %}
        <option value="{{ brand.id }}">{{ brand.name }}</option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Add Product</button>

</form>

{% endblock %}

templates/suppliers/edit.html
{% extends "base.html" %}
{% block content %}

<form action="/suppliers/{{supplier.id}}" method="post">

  <div>
    <label for="supplier">Supplier Name:</label>
    <input type="text" id="supplier" name="name" value="{{supplier.name}}" required autofocus />
  </div>

  <div>
    <label for="contact">Contact Number:</label>
    <input type="text" id="contact" name="contact" value="{{supplier.contact}}" required />
  </div>

  <div>
    <label for="carraige_paid">Carraige Paid:</label>
    <input type="number" id="carraige_paid" name="carraige_paid" value="{{supplier.carraige_paid}}" required />
  </div>


  <button type="submit">Save Supplier</button>

</form>

{% endblock %}

templates/suppliers/index.html
{% extends 'base.html' %}
{% block content  %}  
<style>
table, th, td {
  border:1px solid black;
}
</style>
<body>

<h3>Suppliers</h3>
  
<table style = "width:50%"">
  <tr>
    <th>Supplier</th>
    <th>Telephonic device</th>
    <th>Carraige Paid</th>
  
  </tr>
  

   
  {% for supplier in all_suppliers %}
  <tr>
 
    <!-- <td>{{supplier.name}}</td> -->
    <td> <a href="/suppliers/{{supplier.id}}">{{supplier.name}}</a>  <a href="/suppliers/{{supplier.id}}/edit">Edit</a></td>
    <td>{{supplier.contact}}</td>
    <td>{{supplier.carraige_paid}}</td>





  </tr>
  {% endfor %}

</table>

{% endblock content  %}  

templates/suppliers/new.html
{% extends "base.html" %}
{% block content %}
<h3>Add New Supplier</h3>
<form action="/suppliers" method="post">

  <div>
    <label for="supplier">Supplier Name:</label>
    <input type="text" id="supplier" name="name" placeholder="supplier" required autofocus />
  </div>

  <div>
    <label for="contact">Contact Number:</label>
    <input type="text" id="contact" name="contact" placeholder="contact" required />
  </div>

  <div>
    <label for="carraige_paid">Carraige Paid:</label>
    <input type="number" id="carraige_paid" name="carraige_paid" placeholder="carraige_paid" required />
  </div>


  <button type="submit">Add Supplier</button>

</form>

{% endblock %}

templates/suppliers/show.html
{% extends 'base.html' %}
{% block content  %}  
<style>
table, th, td {
  border:1px solid black;
}
</style>
<body>

<h2>Supplier</h2>
  
<table style = "width:50%"">
  <tr>
    <th>Supplier</th>
    <th>Telephonic device</th>
    <th>Carraige Paid</th>
  
  </tr>
  

   

  <tr>
 
    <!-- <td>{{supplier.name}}</td> -->
    <td>{{supplier.name}}  <a href="/suppliers/{{supplier.id}}/edit">Edit</a></td>
    <td>{{supplier.contact}}</td>
    <td>{{supplier.carraige_paid}}</td>





  </tr>


</table>

{% endblock content  %}  